- source:
    name: "qualys"
    url: "https://api.recruiting.app.silk.security/api/qualys/hosts/get"
- source:
    name: "crowdstrike"
    url: "https://api.recruiting.app.silk.security/api/crowdstrike/hosts/get"
